### ISSUE TITLE
PHPStan configuration

### ISSUE THREAD

**Issue by ezzatron** [kahlan/kahlan#285]
It would be nice to have a drop-in config for Kahlan for [PHPStan](https://github.com/phpstan/phpstan). Currently, when run over a Kahlan project, PHPStan warns about:

- The DSL functions not existing.
- The `$this` keyword used in `kahlan-config.php` outside of a class context.

Here's my current config for handling the first point: 

```yaml
parameters:
  ignoreErrors:
    - /^Function context not found.$/
    - /^Function describe not found.$/
    - /^Function expect not found.$/
    - /^Function it not found.$/
```

But there's probably a better way to fix the problem that doesn't involve "ignoring" these errors. If PHPStan can be configured to understand the functions it could actually pick up on real errors when using them. Are the DSL functions dynamically defined? That would explain why PHPStan complains.

PHPStan uses Neon config files which allow you to include a definition from a vendor, which means that if you created a `kahlan/phpstan-kahlan` repo, users could require it, then add something like this to their PHPStan configuration:

```yaml
includes:
  - vendor/kahlan/phpstan-kahlan/kahlan.neon
```

I just wrote a PHPStan integration for Phony, which is probably more complex than what's needed for Kahlan, but you can check it out [here](https://github.com/eloquent/phpstan-phony) anyway.
